export enum FilterActionType {
  GETFILTERSCONFIG = "GET_FILTERS_CONFIG",
  GETAVAILABLECATEGORIES = "GET_AVAILABLE_CATEGORIES",
  GETAVAILABLECOUNTRIES = "GET_AVAILABLE_CATEGORIES",
  GETAVAILABLEREGIONS = "GET_AVAILABLE_REGIONS",
  UPDATEFILTERCONFIG = "UPDATE_FILTER_CONFIG",
}
