export enum FilterActionType {
  GETFILTERSCONFIG = "GET_FILTERS_CONFIG",
  GETAVAILABLECATEGORIES = "GET_AVAILABLE_CATEGORIES",
  GETAVAILABLECOUNTRIES = "GET_AVAILABLE_CATEGORIES",
  GETAVAILABLEREGIONS = "GET_AVAILABLE_REGIONS",
  SETCATEGORYFILTERCONFIG = "SET_CATEGORY_FILTER_CONFIG",
  SETSELECTEDCOUNTRY = "SET_SELECTED_COUNTRY",
}
